import React from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
AOS.init();
const About = () => {
  return (
    <div className="mb-5" >
      <div className="text-center" >
        <h2 className="text-3xl italic text-center font-bold border-b-2 inline-block ">
          About Us
        </h2>
      </div>

      <p className="text-center text-xl mt-4 px-16">
        THE POWER TOOLS IS A TOOLS BRAND ABOUT PROVIDING TOOLS FOR EVERY HOME. DISTRIBUTING
        HIGH END TOOLS TO HELP CREATE YOUR IDEAL VISION FOR A PROJECT, HOME, OR
        APPLICATION. WE ARE YOUR PARTNERS, CONFIDANTS AND MOST IMPORTANTLY YOUR
        GUIDANCE TO HELP YOU COMPLETE PROJECTS THAT MATTER. WE ARE TENACIOUS,
        EXPRESSIVE, DEDICATED HIGHLY SPECIALIZED IN THE TOOLS SPACE ACROSS
        VARIOUS APPLICATIONS. WE WANT TO SUSTAINABLY DEVELOP WITH OUR
        INTERNATIONAL PARTNERS BY OFFERING THEM TOOLS THAT WIN EVERY SINGLE
        TIME. IT’S THE LITTLE THINGS THAT MAKE A DIFFERENCE, DETAILS MATTER, YOU
        MATTER, AND TOGETHER WE’RE BRINGING EXPERTISE TO OUR CLIENTS THROUGH
        PARTNERSHIP FOR LIFE. WE WANT TO PARTNER WITH YOU, WE WANT YOU TO CHOOSE
        US AS WE CHOOSE YOU. WE KNOW THINGS AREN’T ALWAYS CLEAR, THINGS GET
        MESSY, BUT OUR TEAM WITH OVER YEARS OF EXPERIENCE DEALING WITH CLIENTS
        ACROSS THE WORLD INTERNATIONALLY AND CONSTANTLY FINDING WAYS TO OFFER
        FLEXIBLE SOLUTIONS THAT WORK
      </p>
    </div>
  );
};

export default About;
